# Generated by Django 6.0.4 on 2026-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque como destaque para exibir o destaque no homepage'),
        ),
    ]
